---
- name: add proxy to enviroments
  become: yes
  blockinfile:
    path: /etc/environment
    block: |
      HTTP_PROXY={{proxy_address}}
      HTTPS_PROXY={{proxy_address}}
      http_proxy={{proxy_address}}
      https_proxy={{proxy_address}}
      no_proxy=localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au


- name: make proxy available for current session
  become: yes
  shell: echo 'add proxy configuration success'
  environment:
    http_proxy: "{{ proxy_address }}"
    https_proxy: "{{ proxy_address }}"
    ftp_proxy: "{{ proxy_address }}"
    no_proxy: "localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au"
# add proxy configuration


- name: Update apt
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
# apt-get upgrade; apt-get update

- name: install dependencies
  become: yes
  apt:
    name: ['vim','unzip','git', 'python3-pip','apt-transport-https','ca-certificates','curl','python-setuptools','software-properties-common']
    state: latest
    install_recommends: no
    update_cache: yes

