version: "3.8"

services:
  couchdb:
    environment:
      NODENAME: "{{.Service.Name}}.{{.Task.Slot}}.{{.Task.ID}}"
    image: couchdb:3.1.1
    deploy:
      mode: global
    networks:
      network:
        aliases:
          - couchdb
    ports:
      - "5984:5984"
      - "9100:9100"
      - "4369:4369"
    configs:
      - source: couchdb_conf
    entrypoint: /bin/bash -c "cp -f /couchdb_conf /opt/couchdb/etc/local.d/couch.ini && tini -- /docker-entrypoint.sh /opt/couchdb/bin/couchdb"
networks:
  network:

configs:
  couchdb_conf:
    file: ./couchdb-conf.ini