---
- name: Start a container with a couchdb
  become: yes
  docker_container:
    name: "{{ couchdb_container_name}}"
    image: "{{ couchdb_image }}"
    ports:
      - "5984:5984"
      - "9100:9100"
      - "4369:4369"
    env:
      COUCHDB_PASSWORD: "{{ couchdb_password }}"
      COUCHDB_USER: "{{ couchdb_user }}"
      NODENAME: "{{ ansible_host }}"
      COUCHDB_SECRET: "{{ couchdb_cookie }}"
    volumes:
      - /data:/data
