- hosts: database
  vars_files:
    - host_vars/remote_vars.yaml
  gather_facts: true
  roles:
    - role: deploy-couchdb/install-couchdb

- hosts: leader
  vars_files:
    - host_vars/remote_vars.yaml
  gather_facts: true
  roles:
    - role: deploy-couchdb/setup-cluster
