- hosts: instance1
  vars_files:
    - host_vars/remote_vars.yaml
  gather_facts: true
  roles:
    - role: deploy-applications/git-clone-repository
    - role: deploy-applications/deploy-backend

- hosts: instance2
  vars_files:
    - host_vars/remote_vars.yaml
  gather_facts: true
  roles:
    - role: deploy-applications/git-clone-repository
    - role: deploy-applications/deploy-frontend

- hosts: instance3
  vars_files:
    - host_vars/remote_vars.yaml
  gather_facts: true
  roles:
    - role: deploy-applications/git-clone-repository
    - role: deploy-applications/deploy-crawler
