# - hosts: localhost
#   vars_files:
#     - host_vars/remote_vars.yaml
#   gather_facts: true
#   roles:
#     - role: install-environments/copy-private-key


- hosts: instances
  vars_files:
    - host_vars/remote_vars.yaml
    - host_vars/local_vars.yaml
  gather_facts: true
  roles:
    # - role: install-environments/config-instances
    # - role: install-environments/install-docker
    - role: install-environments/mount-volumns
